title: Stackbit Exto Theme
baseURL: /
params:
  color_scheme: light
  accent_color: pink
  header:
    type: header
    template: header
    title: Allan Froy
    has_nav: true
    nav_links:
      - type: action
        template: action
        label: Home
        url: /
        style: link
      - type: action
        template: action
        label: Blog
        url: /blog/
        style: link
      - type: action
        template: action
        label: About
        url: /about/
        style: link
      - type: action
        template: action
        label: Contact
        url: /contact/
        style: link
    logo_img: /images/Screenshot 2021-03-10 at 11.54.31.png
    logo_img_alt: Allan Froy Logo
  footer:
    type: footer
    template: footer
    content: >-
      &copy; Stackbit. All rights reserved. This Jamstack site was created with
      <a href="https://www.stackbit.com/?utm_source=deployed-footer"
      target="_blank" rel="noopener">Stackbit</a>. Create yours <a
      href="https://app.stackbit.com/create?theme=exto&utm_source=deployed-footer"
      target="_blank" rel="noopener">now</a>
    has_social: true
    social_links:
      - type: action
        template: action
        label: LinkedIn
        url: 'https://www.linkedin.com/'
        style: icon
        icon: linkedin
        new_window: true
  domain: 'https://allanfroy-web-724e6.netlify.app'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
